version: "3.9"

services:
  backend:
    build: ./docker
    command: ["go","run","backend/gen/api/main.go"]
    ports:
      - "8080:8080"
  frontend:
    image: node:20
    working_dir: /app/frontend
    volumes:
      - .:/app
    command: ["elm","make","src/Main.elm","--output=dist/app.js"]
    ports:
      - "5173:5173"
