openapi: 3.0.3
info:
  description: API f√ºr die Berechnung und Darstellung der Berliner Uhr.
  title: Berlin Clock API
  version: 1.0.0
servers:
- url: http://localhost:8080
paths:
  /time:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TimeResponse"
          description: Systemzeit
      summary: Liefert die aktuelle Uhrzeit des Systems.
  /berlin-clock:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BerlinClockState"
          description: Status der Berliner Uhr
      summary: Liefert den aktuellen Status der Berliner Uhr.
components:
  schemas:
    TimeResponse:
      example:
        hour: 0
        minute: 6
        second: 1
      properties:
        hour:
          type: integer
        minute:
          type: integer
        second:
          type: integer
      type: object
    BerlinClockState:
      description: Darstellung aller 5 Reihen der Berliner Uhr.
      example:
        fiveHoursRow:
        - R
        - R
        singleHoursRow:
        - R
        - R
        singleMinutesRow:
        - "Y"
        - "Y"
        secondsLamp: "Y"
        fiveMinutesRow:
        - "Y"
        - "Y"
      properties:
        secondsLamp:
          enum:
          - "Y"
          - O
          type: string
        fiveHoursRow:
          items:
            enum:
            - R
            - O
            type: string
          type: array
        singleHoursRow:
          items:
            enum:
            - R
            - O
            type: string
          type: array
        fiveMinutesRow:
          items:
            enum:
            - "Y"
            - R
            - O
            type: string
          type: array
        singleMinutesRow:
          items:
            enum:
            - "Y"
            - O
            type: string
          type: array
      type: object
